export const examTypes = [
  {
    id: "01",
    title: "Pentaksiran Tingkatan 3 (PT3)",
    value: "PT3",
  },
  {
    id: "02",
    title: "Sijil Pelajaran Malaysia (SPM)",
    value: "SPM",
  },
  {
    id: "03",
    title: "Sijil Tinggi Persekolahan Malaysia (STPM)",
    value: "STPM",
  },
];

export const examCenters = [
  {
    id: "01",
    examCenterCode: "JC005",
    school: "01",
    safeRoomNo: "J01",
    assignmentTasks: ["01", "02", "03"],
  },
  {
    id: "02",
    examCenterCode: "JC017",
    school: "02",
    safeRoomNo: "J02",
    assignmentTasks: ["01", "02", "03"],
  },
  {
    id: "03",
    examCenterCode: "JC013",
    school: "03",
    safeRoomNo: "J03",
    assignmentTasks: ["01", "02", "03"],
  },
];

export const Schools = [
  {
    id: "01",
    name: "SMK Tinggi Kluang",
    schoolCode: "JEB2037",
    examCenters: ["01"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "01",
  },
  {
    id: "02",
    name: "SMK Tengku Aris Bendahara",
    schoolCode: "JEB2038",
    examCenters: ["02"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "02",
  },
  {
    id: "03",
    name: "SMK Sultan Abdul Jalil",
    schoolCode: "JEA2033",
    examCenters: ["03"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "03",
  },
];

export const AssignmentTasks = [
  {
    id: "01",
    title: "SPM 2020",
    examType: "SPM",
    createdDate: "20/03/2020 17:16",
    collectionDate: "21/03/2020 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["01", "02", "03"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Completed" },
      { examCenter: "03", status: "Completed" },
    ],
    chiefInvigilatorComplete: true,
    viceChiefInvigilatorComplete: true,
    invigilatorComplete: true,
    environmentalSupervisorComplete: true,
    roomKeeperComplete: true,
    reservedInvigilatorComplete: true,
    assignmentResults: ["01", "02", "03", "04", "05", "06"],
    status: "Assignment Complete",
  },
  {
    id: "02",
    title: "STPM 2022",
    examType: "STPM",
    createdDate: "20/03/2022 17:16",
    collectionDate: "20/04/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: [],
    collectionStatus: [
      { examCenter: "01", status: "Incomplete" },
      { examCenter: "02", status: "Incomplete" },
      { examCenter: "03", status: "Incomplete" },
    ],
    chiefInvigilatorComplete: false,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: false,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: [],
    status: "Collection in progress",
  },
  {
    id: "03",
    title: "SPM 2022",
    examType: "SPM",
    createdDate: "18/03/2022 17:16",
    collectionDate: "19/03/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["04", "05", "06"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Completed" },
      { examCenter: "03", status: "Completed" },
    ],
    chiefInvigilatorComplete: true,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: true,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: ["07", "08"],
    status: "Assigning in progress",
  },
  {
    id: "04",
    title: "PT3 2022",
    examType: "PT3",
    createdDate: "18/03/2022 17:16",
    collectionDate: "19/03/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["07"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Pending" },
      { examCenter: "03", status: "Incomplete" },
    ],
    chiefInvigilatorComplete: false,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: false,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: [],
    status: "Collection data incomplete",
  },
];

export const examCenterData = [
  {
    id: "01",
    examCenter: "01",
    assignmentTaskId: "01",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 10,
    numberOfReservedInvigilatorRequired: 2,
  },
  {
    id: "02",
    examCenter: "02",
    assignmentTaskId: "01",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 2,
    numberOfInvigilatorRequired: 15,
    numberOfReservedInvigilatorRequired: 2,
  },
  {
    id: "03",
    examCenter: "03",
    assignmentTaskId: "01",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 8,
    numberOfReservedInvigilatorRequired: 1,
  },
  {
    id: "04",
    examCenter: "01",
    assignmentTaskId: "03",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 2,
    numberOfReservedInvigilatorRequired: 1,
  },
  {
    id: "05",
    examCenter: "02",
    assignmentTaskId: "03",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 2,
    numberOfReservedInvigilatorRequired: 1,
  },
  {
    id: "06",
    examCenter: "03",
    assignmentTaskId: "03",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 2,
    numberOfReservedInvigilatorRequired: 1,
  },
  {
    id: "07",
    examCenter: "01",
    assignmentTaskId: "04",
    numberOfChiefInvigilatorRequired: 1,
    numberOfViceChiefInvigilatorRequired: 1,
    numberOfEnvironmentalSupervisorRequired: 1,
    numberOfRoomKeeperRequired: 1,
    numberOfInvigilatorRequired: 8,
    numberOfReservedInvigilatorRequired: 1,
  },
];

export const Invigilators = [
  {
    id: "01",
    name: "MOHD. APANDI B BASIR",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "01",
  },
  {
    id: "02",
    name: "RAJA ROHANI BINTI RAJA HAROON",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "F",
    schoolId: "02",
  },
  {
    id: "03",
    name: "SAMSI BIN ARGI",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "03",
  },
  {
    id: "04",
    name: "Invigilator 04",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "01",
  },
  {
    id: "05",
    name: "Invigilator 05",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "02",
  },
  {
    id: "06",
    name: "Invigilator 06",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "03",
  },
  {
    id: "07",
    name: "Invigilator 07",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "01",
  },
  {
    id: "08",
    name: "Invigilator 08",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "02",
  },
  {
    id: "09",
    name: "Invigilator 09",
    ic: "xxxxx-01-xxxx",
    email: "xxxx@gmail.com",
    gender: "M",
    schoolId: "03",
  },
];

export const AssignmentResults = [
  {
    id: "01",
    assignmentTask: "01",
    role: "chiefInvigilator",
    results: [
      {
        examCenter: "01",
        invigilators: ["03"],
      },
      {
        examCenter: "02",
        invigilators: ["01"],
      },
      {
        examCenter: "03",
        invigilators: ["02"],
      },
    ],
  },
  {
    id: "07",
    assignmentTask: "03",
    role: "chiefInvigilator",
    results: [
      {
        examCenter: "01",
        invigilators: ["03"],
      },
      {
        examCenter: "02",
        invigilators: ["01"],
      },
      {
        examCenter: "03",
        invigilators: ["02"],
      },
    ],
  },
  {
    id: "08",
    assignmentTask: "03",
    role: "invigilator",
    results: [
      {
        examCenter: "01",
        invigilators: ["03", "05"],
      },
      {
        examCenter: "02",
        invigilators: ["01", "06"],
      },
      {
        examCenter: "03",
        invigilators: ["02", "04"],
      },
    ],
  },
];
