export const examCenters = [
  {
    id: "01",
    examCenterCode: "JC005",
    school: "01",
    safeRoomNo: "J01",
    assignmentTasks: ["01", "02", "03", "04"],
  },
  {
    id: "02",
    examCenterCode: "JC017",
    school: "02",
    safeRoomNo: "J02",
    assignmentTasks: ["01", "02", "03", "04"],
  },
  {
    id: "03",
    examCenterCode: "JC013",
    school: "03",
    safeRoomNo: "J03",
    assignmentTasks: ["01", "02", "03", "04"],
  },
];

export const Schools = [
  {
    id: "01",
    name: "SMK Tinggi Kluang",
    schoolCode: "JEB2037",
    examCenters: ["01"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "01",
  },
  {
    id: "02",
    name: "SMK Tengku Aris Bendahara",
    schoolCode: "JEB2038",
    examCenters: ["02"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "02",
  },
  {
    id: "03",
    name: "SMK Sultan Abdul Jalil",
    schoolCode: "JEA2033",
    examCenters: ["03"],
    address: "xxxx, Jalan XXX, 81000, XXX, Johor",
    examSecretary: "03",
  },
];

export const AssignmentTasks = [
  {
    id: "01",
    title: "SPM 2020",
    examType: "SPM",
    createdDate: "20/03/2020 17:16",
    collectionDate: "21/03/2020 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["01", "02", "03"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Completed" },
      { examCenter: "03", status: "Completed" },
    ],
    chiefInvigilatorComplete: true,
    viceChiefInvigilatorComplete: true,
    invigilatorComplete: true,
    environmentalSupervisorComplete: true,
    roomKeeperComplete: true,
    reservedInvigilatorComplete: true,
    assignmentResults: ["01", "02", "03", "04", "05", "06"],
    status: "Assignment Complete",
  },
  {
    id: "02",
    title: "STPM 2022",
    examType: "STPM",
    createdDate: "20/03/2022 17:16",
    collectionDate: "20/04/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: [],
    collectionStatus: [
      { examCenter: "01", status: "Incomplete" },
      { examCenter: "02", status: "Incomplete" },
      { examCenter: "03", status: "Incomplete" },
    ],
    chiefInvigilatorComplete: false,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: false,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: [],
    status: "Collection in progress",
  },
  {
    id: "03",
    title: "SPM 2022",
    examType: "SPM",
    createdDate: "18/03/2022 17:16",
    collectionDate: "19/03/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["04", "05", "06"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Completed" },
      { examCenter: "03", status: "Completed" },
    ],
    chiefInvigilatorComplete: true,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: true,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: ["07", "08"],
    status: "Assigning in progress",
  },
  {
    id: "04",
    title: "PT3 2022",
    examType: "PT3",
    createdDate: "18/03/2022 17:16",
    collectionDate: "19/03/2022 00:00",
    examCenters: ["01", "02", "03"],
    examCenterData: ["07"],
    collectionStatus: [
      { examCenter: "01", status: "Completed" },
      { examCenter: "02", status: "Pending" },
      { examCenter: "03", status: "Incomplete" },
    ],
    chiefInvigilatorComplete: false,
    viceChiefInvigilatorComplete: false,
    invigilatorComplete: false,
    environmentalSupervisorComplete: false,
    roomKeeperComplete: false,
    reservedInvigilatorComplete: false,
    assignmentResults: [],
    status: "Collection data incomplete",
  },
];

export const examSecretaries = [
  {
    id: "01",
    school: "01",
    username: "sec01",
    password: "123456",
  },
  {
    id: "02",
    school: "02",
    username: "sec02",
    password: "123456",
  },
  {
    id: "03",
    school: "03",
    username: "sec03",
    password: "123456",
  },
  {
    id: "04",
    school: "04",
    username: "sec04",
    password: "123456",
  },
];
